//
//  Data.swift
//  Water-tracker
//
//  Created by Artem Golovanev on 18.03.2019.
//  Copyright © 2019 Artem Golovanev. All rights reserved.
//

import Foundation

struct Data {

    let range: [Quantity] =
        [Quantity(description: "30 min", quantity: 1800),
         Quantity(description: "1 hour", quantity: 3600),
         Quantity(description: "1 hour 30 min", quantity: 5400),
         Quantity(description: "2 hour", quantity: 7200),
         Quantity(description: "3 hour", quantity: 10800),]


    let ml: [Quantity] =
        [Quantity(description: "100ml", quantity: 100),
         Quantity(description: "150ml", quantity: 150),
         Quantity(description: "200ml", quantity: 200),
         Quantity(description: "250ml", quantity: 250),
         Quantity(description: "300ml", quantity: 300),
         Quantity(description: "350ml", quantity: 350),
         Quantity(description: "400ml", quantity: 400),
         Quantity(description: "450ml", quantity: 450),
         Quantity(description: "500ml", quantity: 500),
         Quantity(description: "550ml", quantity: 550),
         Quantity(description: "600ml", quantity: 600),
         Quantity(description: "650ml", quantity: 650),
         Quantity(description: "700ml", quantity: 700),
         Quantity(description: "750ml", quantity: 750),
         Quantity(description: "800ml", quantity: 800),
         Quantity(description: "850ml", quantity: 850),
         Quantity(description: "900ml", quantity: 900),
         Quantity(description: "950ml", quantity: 950),
         Quantity(description: "1000ml", quantity: 1000),
         Quantity(description: "1050ml", quantity: 1050),
         Quantity(description: "1100ml", quantity: 1100),
         Quantity(description: "1150ml", quantity: 1150),
         Quantity(description: "1200ml", quantity: 1200),
         Quantity(description: "1250ml", quantity: 1250),
         Quantity(description: "1300ml", quantity: 1300),
         Quantity(description: "1350ml", quantity: 1350),
         Quantity(description: "1400ml", quantity: 1400),
         Quantity(description: "1450ml", quantity: 1450),
         Quantity(description: "1500ml", quantity: 1500),
         Quantity(description: "1550ml", quantity: 1550),
         Quantity(description: "1600ml", quantity: 1600),
         Quantity(description: "1650ml", quantity: 1650),
         Quantity(description: "1700ml", quantity: 1700),
         Quantity(description: "1750ml", quantity: 1750),
         Quantity(description: "1800ml", quantity: 1800),
         Quantity(description: "1850ml", quantity: 1850),
         Quantity(description: "1900ml", quantity: 1900),
         Quantity(description: "1950ml", quantity: 1950),
         Quantity(description: "2000ml", quantity: 2000),
         Quantity(description: "2050ml", quantity: 2050),
         Quantity(description: "2100ml", quantity: 2100),
         Quantity(description: "2150ml", quantity: 2150),
         Quantity(description: "2200ml", quantity: 2200),
         Quantity(description: "2250ml", quantity: 2250),
         Quantity(description: "2300ml", quantity: 2300),
         Quantity(description: "2350ml", quantity: 2350),
         Quantity(description: "2400ml", quantity: 2400),
         Quantity(description: "2450ml", quantity: 2450),
         Quantity(description: "2500ml", quantity: 2500),
         Quantity(description: "2550ml", quantity: 2550),
         Quantity(description: "2600ml", quantity: 2600),
         Quantity(description: "2650ml", quantity: 2650),
         Quantity(description: "2700ml", quantity: 2700),
         Quantity(description: "2750ml", quantity: 2750),
         Quantity(description: "2800ml", quantity: 2800),
         Quantity(description: "2850ml", quantity: 2850),
         Quantity(description: "2900ml", quantity: 2900),
         Quantity(description: "2950ml", quantity: 2950),
         Quantity(description: "3000ml", quantity: 3000),
         Quantity(description: "3050ml", quantity: 3050),
         Quantity(description: "3100ml", quantity: 3100),
         Quantity(description: "3150ml", quantity: 3150),
         Quantity(description: "3200ml", quantity: 3200),
         Quantity(description: "3250ml", quantity: 3250),
         Quantity(description: "3300ml", quantity: 3300),
         Quantity(description: "3350ml", quantity: 3350),
         Quantity(description: "3400ml", quantity: 3400),
         Quantity(description: "3450ml", quantity: 3450),
         Quantity(description: "3500ml", quantity: 3500),
         Quantity(description: "3550ml", quantity: 3550),
         Quantity(description: "3600ml", quantity: 3600),
         Quantity(description: "3650ml", quantity: 3650),
         Quantity(description: "3700ml", quantity: 3700),
         Quantity(description: "3750ml", quantity: 3750),
         Quantity(description: "3800ml", quantity: 3800),
         Quantity(description: "3850ml", quantity: 3850),
         Quantity(description: "3900ml", quantity: 3900),
         Quantity(description: "3950ml", quantity: 3950),
         Quantity(description: "4000ml", quantity: 4000),
         ]

    let kg: [Quantity] =
        [(Quantity(description: "30kg", quantity: 30)),
         (Quantity(description: "31kg", quantity: 31)),
         (Quantity(description: "32kg", quantity: 32)),
         (Quantity(description: "33kg", quantity: 33)),
         (Quantity(description: "34kg", quantity: 34)),
         (Quantity(description: "35kg", quantity: 35)),
         (Quantity(description: "36kg", quantity: 36)),
         (Quantity(description: "37kg", quantity: 37)),
         (Quantity(description: "38kg", quantity: 38)),
         (Quantity(description: "39kg", quantity: 39)),
         (Quantity(description: "40kg", quantity: 40)),
         (Quantity(description: "41kg", quantity: 41)),
         (Quantity(description: "42kg", quantity: 42)),
         (Quantity(description: "43kg", quantity: 43)),
         (Quantity(description: "44kg", quantity: 44)),
         (Quantity(description: "45kg", quantity: 45)),
         (Quantity(description: "46kg", quantity: 46)),
         (Quantity(description: "47kg", quantity: 47)),
         (Quantity(description: "48kg", quantity: 48)),
         (Quantity(description: "49kg", quantity: 49)),
         (Quantity(description: "50kg", quantity: 50)),
         (Quantity(description: "51kg", quantity: 51)),
         (Quantity(description: "52kg", quantity: 52)),
         (Quantity(description: "53kg", quantity: 53)),
         (Quantity(description: "54kg", quantity: 54)),
         (Quantity(description: "55kg", quantity: 55)),
         (Quantity(description: "56kg", quantity: 56)),
         (Quantity(description: "57kg", quantity: 57)),
         (Quantity(description: "58kg", quantity: 58)),
         (Quantity(description: "59kg", quantity: 59)),
         (Quantity(description: "60kg", quantity: 60)),
         (Quantity(description: "61kg", quantity: 61)),
         (Quantity(description: "62kg", quantity: 62)),
         (Quantity(description: "63kg", quantity: 63)),
         (Quantity(description: "64kg", quantity: 64)),
         (Quantity(description: "65kg", quantity: 65)),
         (Quantity(description: "66kg", quantity: 66)),
         (Quantity(description: "67kg", quantity: 67)),
         (Quantity(description: "68kg", quantity: 68)),
         (Quantity(description: "69kg", quantity: 69)),
         (Quantity(description: "70kg", quantity: 70)),
         (Quantity(description: "71kg", quantity: 71)),
         (Quantity(description: "72kg", quantity: 72)),
         (Quantity(description: "73kg", quantity: 73)),
         (Quantity(description: "74kg", quantity: 74)),
         (Quantity(description: "75kg", quantity: 75)),
         (Quantity(description: "76kg", quantity: 76)),
         (Quantity(description: "77kg", quantity: 77)),
         (Quantity(description: "78kg", quantity: 78)),
         (Quantity(description: "79kg", quantity: 79)),
         (Quantity(description: "80kg", quantity: 80)),
         (Quantity(description: "81kg", quantity: 81)),
         (Quantity(description: "82kg", quantity: 82)),
         (Quantity(description: "83kg", quantity: 83)),
         (Quantity(description: "84kg", quantity: 84)),
         (Quantity(description: "85kg", quantity: 85)),
         (Quantity(description: "86kg", quantity: 86)),
         (Quantity(description: "87kg", quantity: 87)),
         (Quantity(description: "88kg", quantity: 88)),
         (Quantity(description: "89kg", quantity: 89)),
         (Quantity(description: "90kg", quantity: 90)),
         (Quantity(description: "91kg", quantity: 91)),
         (Quantity(description: "92kg", quantity: 92)),
         (Quantity(description: "93kg", quantity: 93)),
         (Quantity(description: "94kg", quantity: 94)),
         (Quantity(description: "95kg", quantity: 95)),
         (Quantity(description: "96kg", quantity: 96)),
         (Quantity(description: "97kg", quantity: 97)),
         (Quantity(description: "98kg", quantity: 98)),
         (Quantity(description: "99kg", quantity: 99)),
         (Quantity(description: "100kg", quantity: 100)),
         (Quantity(description: "101kg", quantity: 101)),
         (Quantity(description: "102kg", quantity: 102)),
         (Quantity(description: "103kg", quantity: 103)),
         (Quantity(description: "104kg", quantity: 104)),
         (Quantity(description: "105kg", quantity: 105)),
         (Quantity(description: "106kg", quantity: 106)),
         (Quantity(description: "107kg", quantity: 107)),
         (Quantity(description: "108kg", quantity: 108)),
         (Quantity(description: "109kg", quantity: 109)),
         (Quantity(description: "110kg", quantity: 110))]

    let drinks: [ReciveImagesToDrinks] =
        [ReciveImagesToDrinks(image: "water", name: "Water", coefficient: "1"),
         ReciveImagesToDrinks(image: "milk", name: "Milk", coefficient: "0.78"),
         ReciveImagesToDrinks(image: "kefir", name: "Kefir", coefficient: "0.6"),
         ReciveImagesToDrinks(image: "tea", name: "Tea", coefficient: "0.85"),
         ReciveImagesToDrinks(image: "coffee", name: "Coffee", coefficient: "0.8"),
         ReciveImagesToDrinks(image: "cold coffee", name: "Cold coffee", coefficient: "0.72"),
         ReciveImagesToDrinks(image: "lemonade", name: "Lemonade", coefficient: "0.6"),
         ReciveImagesToDrinks(image: "cola", name: "Coca-Cola", coefficient: "0.6"),
         ReciveImagesToDrinks(image: "juice", name: "Juice", coefficient: "0.55"),
         ReciveImagesToDrinks(image: "smoothie", name: "Smoothie", coefficient: "0.33"),
         ReciveImagesToDrinks(image: "energy", name: "Energy drink", coefficient: "0.4"),
         ReciveImagesToDrinks(image: "non-alcoholic beer", name: "Beer (n/a)", coefficient: "0.6"),
         ReciveImagesToDrinks(image: "non-alcoholic coctail", name: "Coctail (n/a)", coefficient: "0.5"),
         ReciveImagesToDrinks(image: "beer", name: "Beer", coefficient: "-0.6"),
         ReciveImagesToDrinks(image: "champagne", name: "Champagne", coefficient: "-1.8"),
         ReciveImagesToDrinks(image: "wine", name: "Wine", coefficient: "-1.8"),
         ReciveImagesToDrinks(image: "whiskey", name: "Whiskey", coefficient: "-3.5"),
         ReciveImagesToDrinks(image: "brandy", name: "Brandy", coefficient: "-3.5"),
         ReciveImagesToDrinks(image: "vodka", name: "Vodka", coefficient: "-3.5"),
         ReciveImagesToDrinks(image: "cognac", name: "Cognac", coefficient: "-3.5"),
         ReciveImagesToDrinks(image: "cocktail", name: "Coctail", coefficient: "-2.0"),
         ReciveImagesToDrinks(image: "shot", name: "Shot", coefficient: "-1.5"),
         ReciveImagesToDrinks(image: "tincture", name: "Tincture", coefficient: "-3.5"),
         ReciveImagesToDrinks(image: "other", name: "Other", coefficient: "0.5")]
}
